#!/bin/sh

if [ "$#" -ne 2 ]; then
  echo "illegal number of parameters. You should specify an input .gcode file and an output png/jpg file"
fi

sed -n '/thumbnail begin/,/thumbnail end/p;' "$1" | sed '$d;1d; s/^; //;' | sed -z "s/\n//g" | base64 -d - > "$2"
